name: "Deploy to Env"
description: "Deploy to an environment"

inputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-account-id:
    description: "AWS Account ID"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  eks-cluster-name:
    description: "EKS Cluster Name"
    required: true
  service-name:
    description: "Service Name"
    required: true
  chart-dir:
    description: "Chart Directory"
    required: true
  values-filename:
    description: "Values Filename (relative to chart-dir)"
    required: true
  namespace:
    description: "Namespace"
    required: true
  image-version:
    description: "Image Version"
    required: true

runs:
  using: composite
  steps:
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-account-id: ${{ inputs.aws-account-id }}
        aws-region: ${{ inputs.aws-region }}
    - name: Configure Kube Config
      shell: 'bash'
      run: |
        aws eks update-kubeconfig --name ${{ inputs.eks-cluster-name }}  --region ${{ inputs.aws-region }}
    - name: Setup Helm
      uses: azure/setup-helm@v4
    - name: Helm upgrade/install
      shell: 'bash'
      run: |
        helm upgrade ${{ inputs.service-name }} ${{ inputs.chart-dir }} -f ${{ inputs.chart-dir }}/values.yaml -f ${{ inputs.chart-dir }}/${{ inputs.values-filename }} --namespace ${{ inputs.namespace }} --install
    - name: Update Image Version
      shell: 'bash'
      run: |
        kubectl set image deployment/${{ inputs.service-name }} ${{ inputs.service-name }}=750966670282.dkr.ecr.us-west-2.amazonaws.com/${{ inputs.service-name }}:${{ inputs.image-version }} --namespace=${{ inputs.namespace }}
